version: "3.9"

services:
  mcp-server:
    build: ./mcp-server
    env_file: .env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - MILVUS_URI=http://milvus-standalone:19530
    volumes:
      - ./:/data/project:ro
    working_dir: /usr/src/app
    command: ["node", "build/index.js", "--http", "--port", "8080", "--docs-path", "/data/project", "--embed-model", "voyage-3-large"]
    ports:
      - "8080:8080"
    depends_on:
      - milvus-standalone

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: ["etcd", "-advertise-client-urls=http://etcd:2379", "-listen-client-urls=http://0.0.0.0:2379", "-initial-advertise-peer-urls=http://etcd:2380", "-listen-peer-urls=http://0.0.0.0:2380", "-initial-cluster=etcd=http://etcd:2380", "-initial-cluster-state=new", "-name=etcd"]

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: ["minio", "server", "/data/minio", "--console-address", ":9001"]
    ports:
      - "9001:9001"

  milvus-standalone:
    image: milvusdb/milvus:v2.6.4
    depends_on:
      - etcd
      - minio
    ports:
      - "19530:19530"
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    command: ["milvus", "run", "standalone"]
