name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: Install
        run: npm ci
        working-directory: mcp-server
      - name: Build
        run: npm run build
        working-directory: mcp-server
      - name: Unit tests
        run: npm run test:unit
        working-directory: mcp-server
      - name: Integration tests (if secrets present)
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY || '' }}
          VOYAGE_API_KEY: ${{ secrets.VOYAGE_API_KEY || '' }}
          COHERE_API_KEY: ${{ secrets.COHERE_API_KEY || '' }}
        if: ${{ env.GROQ_API_KEY != '' || env.VOYAGE_API_KEY != '' || env.COHERE_API_KEY != '' }}
        run: npm run test:integration
        working-directory: mcp-server


