name: Claude PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  claude-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get PR diff
        id: diff
        run: |
          # Get the diff for the PR
          gh pr diff ${{ github.event.pull_request.number }} > pr.diff

          # Check if diff is too large (Claude has token limits)
          DIFF_SIZE=$(wc -c < pr.diff)
          if [ $DIFF_SIZE -gt 100000 ]; then
            echo "diff_too_large=true" >> $GITHUB_OUTPUT
            echo "Diff size: $DIFF_SIZE bytes (too large for review)"
          else
            echo "diff_too_large=false" >> $GITHUB_OUTPUT
            echo "Diff size: $DIFF_SIZE bytes"
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Review PR with Claude
        if: steps.diff.outputs.diff_too_large == 'false'
        id: claude_review
        run: |
          # Read the diff
          DIFF=$(cat pr.diff)

          # Create the prompt for Claude
          PROMPT="You are a code reviewer. Please review the following pull request changes and provide constructive feedback.

Focus on:
1. Code quality and best practices
2. Potential bugs or issues
3. Performance considerations
4. Security concerns
5. Documentation and comments
6. Testing coverage

Here's the PR description:
Title: ${{ github.event.pull_request.title }}
Description: ${{ github.event.pull_request.body }}

Here are the changes:
\`\`\`diff
${DIFF}
\`\`\`

Please provide a detailed review with specific suggestions for improvement."

          # Call Claude API
          RESPONSE=$(curl -s https://api.anthropic.com/v1/messages \
            -H "content-type: application/json" \
            -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
            -H "anthropic-version: 2023-06-01" \
            -d @- <<EOF
{
  "model": "claude-3-5-sonnet-20241022",
  "max_tokens": 4096,
  "messages": [
    {
      "role": "user",
      "content": $(echo "$PROMPT" | jq -Rs .)
    }
  ]
}
EOF
)

          # Extract the review text
          REVIEW=$(echo "$RESPONSE" | jq -r '.content[0].text')

          # Save review to file
          echo "$REVIEW" > review.md

      - name: Post review comment
        if: steps.diff.outputs.diff_too_large == 'false'
        run: |
          REVIEW=$(cat review.md)

          gh pr comment ${{ github.event.pull_request.number }} --body "## 🤖 Claude AI Code Review

${REVIEW}

---
*This review was automatically generated by Claude AI*"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Post size warning
        if: steps.diff.outputs.diff_too_large == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "## ⚠️ PR Too Large for Automated Review

This PR is too large for automated review by Claude AI. Please consider:
- Breaking it into smaller PRs
- Requesting manual review from maintainers

---
*This message was automatically generated*"
        env:
          GH_TOKEN: ${{ github.token }}
